apps/alumnado/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from apps.alumnado import views as alumnado_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', alumnado_views.alumnado_vista, name="alumnado_vista"),
    # path('signup/', views.SignUp.as_view(), name='signup'),    
    # path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('alumnos/', login_required(alumnado_views.alumno_lista), name="alumno_lista"),
    path('alumnos/editar/<pk>', login_required(alumnado_views.alumno_edit), name="alumno_editar"),
    path('alumnos/delete/<pk>', login_required(alumnado_views.alumno_delete), name="alumno_delete"),
    path('alumno_api', login_required(alumnado_views.AlumnoApi.as_view()), name ="alumno_api"),
    path('materia_search_api', login_required(alumnado_views.MateriaSearchApi.as_view()), name ="materia_search_api"),
    path('maestro_search_api', login_required(alumnado_views.MaestroSearchApi.as_view()), name ="maestro_search_api"),
]

sistema_escuela/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic import TemplateView
from apps.alumnado import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('alumnado/', include(('apps.alumnado.urls', "alumnado"), namespace="alumnado")),
    path('', TemplateView.as_view(template_name='sistema_escuela/home.html')),

]

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/alumnado/models.py
# -*- encoding: utf-8 -*-
from django.db import models

# Create your models here.
class Materia(models.Model):
    nombre_materia = models.TextField(max_length=100)
    descripcion_materia = models.TextField()

    def __str__(self):
        return self.nombre_materia



class Maestro(models.Model):
    nombre_maestro = models.CharField(max_length=100)
    apellidos_maestro = models.CharField(max_length=100)
    fecha_nacimiento_maestro = models.DateField()
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_maestro


class Alumno(models.Model):
    nombre_alumno = models.CharField(max_length=100)
    apellidos_alumno = models.CharField(max_length=100)
    fecha_nacimiento_alumno = models.DateField()
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    maestro = models.ForeignKey(Maestro, on_delete=models.CASCADE)
    disponible = models.BooleanField(default = True)

    def __str__(self):
        return self.nombre_alumno

apps/comun/models.py
from django.db import models

# Create your models here.

apps/alumnado/forms.py
from django import forms
from .models import Materia, Maestro, Alumno


class MateriaForm(forms.ModelForm):

    class Meta:
        model = Materia
        fields = [
            'nombre_materia',
            'descripcion_materia',
        ]


class MaestroForm(forms.ModelForm):

    class Meta:
        model = Maestro
        fields = [
            'nombre_maestro',
            'apellidos_maestro',
            'fecha_nacimiento_maestro',
            'materia',
        ]


class AlumnoForm(forms.ModelForm):

    class Meta:
        model = Alumno
        template = 'alumnado/alumnado_new.html'
        fields = ('nombre_alumno', 'apellidos_alumno', 
        'fecha_nacimiento_alumno', 'materia', 'maestro',
        )

        widgets = {
            'nombre_alumno': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Nombre'}),
            'apellidos_alumno': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Apellido'}),
            'fecha_nacimiento_alumno': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Fecha de nacimiento'}),
            'materia': forms.Select(attrs={'class': 'form-control'}),
            'maestro': forms.Select(attrs={'class': 'form-control'}),
        }

        help_text = {
            'nombre_alumno': None,
            'apellido_alumno': None,
            'fecha_nacimiento_alumno': None,
            'materia': None,
            'maestro': None,

        }

apps/accounts/views.py
from django.shortcuts import render

# Create your views here.

apps/alumnado/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.alumnado.serializers import AlumnoSerializers
from apps.alumnado.services import AlumnoServices, MateriaServices, MaestroServices
from .forms import AlumnoForm
from apps.alumnado.models import Materia, Maestro, Alumno
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic



# Create your views here.
# funcion para crear una materia
# def crear_materia(request):
#     if request.method == 'POST':
#         form = MateriaForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('home')
#     else:
#         form = MateriaForm()
#     return render(request, 'alumnado/crear_materia.html',{'form':form})

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


def alumnado_vista(request):
    return render(request, 'alumnado/alumnado.html')


def alumno_lista(request):
    alumnos = Alumno.objects.filter(disponible = True)
    return render(request, 'alumnado/alumnos_lista.html')
    # return render(request, 'alumnado/alumnos_lista.html', {'alumnos': alumnos})


class AlumnoApi(APIView):
    def get(self, request):
        return Response(AlumnoServices.get_list())

    def post(self, request):
        response_data = {}
        try:
            response_data['success'] = AlumnoServices.guardar(request.data)
            response_data['message'] = 'El alumno se ha guardado'
        except Exception as e:
            response_data['success'] = False
            response_data['error'] = str(e)
        return Response(response_data)

    def delete(self, request):
        response_data = {}
        try:
            response_data['success'] = AlumnoServices.inactive(request.data)
            response_data['message'] = 'El alumno se ha eliminado'
        except Exception as e:
            response_data['success'] = False
            response_data['error'] = str(e)
        return Response(response_data)

def alumno_edit(request, pk):
    alumno = Alumno.objects.get(pk=pk)
    if request.method == "POST":
        form = AlumnoForm(request.POST, instance=alumno)
        if form.is_valid():
            alumno = form.save(commit=False)
            alumno.save()
            return redirect('alumno_lista')
    else:
        form = AlumnoForm(instance=alumno)
    return render(request, 'alumnado/alumnos_edit.html', {'form': form})


def alumno_delete(request, pk):
    alumno = Alumno.objects.get(pk=pk)
    print (alumno.disponible)
    alumno.disponible = not alumno.disponible
    print (alumno.disponible)
    alumno.save()
    # alumno.delete()
    return redirect('alumno_lista')


class MateriaSearchApi(APIView):
    def get(self, request):
        term = request.GET.get('term[term]', '')
        if term != '':
            print(term)
        return HttpResponse(MateriaServices.get_options(term=term), 'applications/json')


class MaestroSearchApi(APIView):
    def get(self, request):
        term = request.GET.get('term[term]', '')
        if term != '':
            print(term)
        return HttpResponse(MaestroServices.get_options(term=term), 'applications/json')

apps/comun/views.py
from django.shortcuts import render

# Create your views here.

apps/alumnado/templates/alumnado/alumnado.html
{% extends 'sistema_escuela/base.html' %}


{% block content %}

<h1>Bienvenido a Alumnado</h1>

<ul>
    <li><a href="#">Alumnos</a></li>
    <li><a href="#">Materias</a></li>
    <li><a href="#">Maestros</a></li>
</ul>

{% endblock %}

apps/alumnado/templates/alumnado/alumno_new.html
<div class="container">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info btn-lg" id="modal-alumno-new">Nuevo Alumno</button>
    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">

                <div class="modal-body form-group">
                    <form id="form_new_alumno">
                        <input type="hidden" name="id" id="id">
            <p><label for="id_nombre_alumno">Nombre alumno:</label>
            <input type="text" name="nombre_alumno" class="form-control" placeholder="Nombre del Alumno" maxlength="100" id="id_nombre_alumno"></p>
            <p><label for="id_apellidos_alumno">Apellidos alumno:</label>
            <input type="text" name="apellidos_alumno" class="form-control" placeholder="Apellido" maxlength="100" id="id_apellidos_alumno"></p>
            <p><label for="id_fecha_nacimiento_alumno">Fecha nacimiento alumno:</label>
            <input type="text" name="fecha_nacimiento_alumno" class="form-control" placeholder="Fecha de nacimiento" id="id_fecha_nacimiento_alumno" autocomplete="off"></p>
            <p><label for="id_materia">Materia:</label>
            <select name="materia" class="js-states form-control" id="id_materia">
           </select></p>
            <p><label for="id_maestro">Maestro:</label>
            <select name="maestro" class="js-states form-control" id="id_maestro">

            </select>
            </p><button type="button" class="btn btn-primary" id="button-alumno-new-crear"><span class="glyphicon glyphicon-plus-sign"></span> Crear </button>

                        <button type="button" class="btn btn-danger" id="modal-alumno-new-close" data-dismiss="modal"><span class="glyphicon glyphicon-remove-sign"></span> Close</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

apps/alumnado/templates/alumnado/alumnos_edit.html
{% extends 'sistema_escuela/base.html' %}

{% load static %}

{% block content %}

<h2>Editar Alumno</h2>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Editar</button>
</form>

{% endblock %}

apps/alumnado/templates/alumnado/alumnos_lista.html
{% extends 'sistema_escuela/base.html' %}
{% load static %}
{% block content %}
    <h2>Alumnos</h2>
{% include 'alumnado/alumno_new.html' %}
    <table id="datatables" class="table table-hover"><thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Fecha</th>
            <th>Materia</th>
            <th>Maestro</th>
            <th>Edad</th>
            <th>Acciones</th>


        </tr>
        </thead>
    </table>

{% endblock %}

{% block js %}

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script type="text/javascript" src="{% static 'js/csrftoken.js' %}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.js"></script>
    <script src="{% static 'alumnado/alumnos.js' %}"></script>
    <script>
        $(document).ready(function () {
            $.datepicker.regional['es'] = {
                closeText: 'Cerrar',
                prevText: '<Ant',
                nextText: 'Sig>',
                currentText: 'Hoy',
                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                monthNamesShort: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
                dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
                weekHeader: 'Sm',
                dateFormat: 'dd/mm/yy',
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ''
            };
            $.datepicker.setDefaults($.datepicker.regional['es']);

            var tabla_alumno = $('#datatables').DataTable({
                ajax: {
                    url: "{% url 'alumnado:alumno_api' %}",
                    dataSrc: ""
                },
                columns: [
                    {data: "id"},
                    {data: "nombre_alumno"},
                    {data: "apellidos_alumno"},
                    {data: "fecha_nacimiento_alumno"},
                    {data: "materia_name"},
                    {data: "maestro_name"},
                    {data: "age"}
                ],
                "createdRow": function (row, data, dataIndex) {
                    var delete_button = $('<button>').click(function () {
                        $.ajax({
                            url: '{% url "alumnado:alumno_api" %}',
                            dataType: "json",
                            type: 'delete',
                            data: {'id': data.id}
                        }).done(function (response) {
                            if (response.success) {
                                alert(response.message)
                            } else {
                                alert(response.error)
                            }
                        }).always(function () {
                            tabla_alumno.ajax.reload();
                        });
                    }).addClass('far fa-trash-alt').text('Eliminar');

                    var edit_button_modal = $('<button>').click(function () {
                        alumno_edit(data);
                    }).addClass('far fa-edit').text('Editar');

                    var td = $('<td>');
                    td.append(edit_button_modal, delete_button);
                    $(row).append(td);
                }
            });

            var fecha = $('#id_fecha_nacimiento_alumno').datepicker({
                    showOtherMonths: true,
                    dateFormat: 'yy-mm-dd',
                    changeYear: true,
                    yearRange: '1900:2100',
                    changeMonth: true
            });
            var materia_select2 = $('#id_materia').select2({
                    ajax: {
                        url: "{% url 'alumnado:materia_search_api' %}",
                        dataType: 'json',
                        type: "GET",
                        quietMillis: 50,
                        data: function (term) {
                            return {
                                term: term
                            };
                        },
                        processResults: function (data, params) {
                            console.log(data)
                            console.log(params)
                            return {
                                results: data
                            };
                        },
                        results: function (data) {
                            console.log(data)
                            return {
                                results: $.map(data, function (item) {
                                    return {
                                        text: item.completeName,
                                        id: item.id
                                    }
                                })
                            };
                        }
                    },
                    width: '100%'
                });
            var maestro_select2 = $('#id_maestro').select2({
                    ajax: {
                        url: "{% url 'alumnado:maestro_search_api' %}",
                        dataType: 'json',
                        type: "GET",
                        quietMillis: 50,
                        data: function (term) {
                            return {
                                term: term
                            };
                        },
                        processResults: function (data, params) {
                            console.log(data)
                            console.log(params)
                            return {
                                results: data
                            };
                        },
                        results: function (data) {
                            console.log(data)
                            return {
                                results: $.map(data, function (item) {
                                    return {
                                        text: item.completeName,
                                        id: item.id
                                    }
                                })
                            };
                        }
                    },
                    width: '100%'
                });

            var alumno_edit = function(data){
                console.log(data);
                limpiar();
                $('#id').val(data.id);
                $('#id_nombre_alumno').val(data.nombre_alumno);
                $('#id_apellidos_alumno').val(data.apellidos_alumno);
                $('#id_fecha_nacimiento_alumno').datepicker('setDate', data.fecha_nacimiento_alumno);
                var materia_select = $('#id_materia');
                materia_select.children().remove();
                var option_materia = $('<option>').text(data.materia_json.text).val(data.materia_json.id);
                materia_select.append(option_materia);
                materia_select.val(data.materia).trigger('change');
                var maestro_select = $('#id_maestro');
                maestro_select.children().remove();
                var opcion_maestro = $('<option>').text(data.maestro_json.text).val(data.maestro_json.id);
                maestro_select.append(opcion_maestro);
                maestro_select.val(data.maestro).trigger('change');
                $('#myModal').modal({
                    keyboard: false,
                    backdrop: 'static'
                });
            };

            $('#modal-alumno-new').click(function () {
                limpiar();
                $('#myModal').modal({
                    keyboard: false,
                    backdrop: 'static'
                });
            });

            var limpiar = function () {
                $('#id').val(0);
                $('#id_nombre_alumno').val('');
                $('#id_apellidos_alumno').val('');
                $('#id_fecha_nacimiento_alumno').datepicker('setDate', 'today');
                $('#id_materia').val(null).trigger('change');
                $('#id_maestro').val(null).trigger('change');
            };


            $('#modal-alumno-new-close').click(function () {
                $('#myModal').modal('hide')
            });


            var config = {
                url_post_nuevo_alumno: '{% url "alumnado:alumno_api" %}',
                tabla: tabla_alumno
            };
            var alumnos = new Alumnos();
            alumnos.init(config);

        });
    </script>

{% endblock js %}

templates/sistema_escuela/base.html
<html lang="en">
{% load static %}

<head>
  <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">


<!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>

  

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Sistema Escuela{% endblock %}</title>
</head>

<body>
<!--  <nav>-->
<!--        <a href="{% url 'alumnado:alumnado_vista' %}">Inicio</a>-->
<!--        <a href="{% url 'alumnado:alumno_lista' %}">Alumnado</a>-->
<!--        <a href="#">Registrar</a>-->
<!--        <a href="{% url 'login' %}">Entrar</a>-->
<!--    </nav>-->
  {% block sidebar %}
  <nav class="navbar navbar-expand-lg class=" navbar navbar-light" style="background-color: #D3F1EF;">
    <a class="navbar-brand" href="{% url 'alumnado:alumnado_vista' %}"><span class="glyphicon glyphicon-home"></span> Inicio</a>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'alumnado:alumno_lista' %}"><span class="
glyphicon glyphicon-list-alt"></span> Lista Alumnos<span
            class="sr-only">(current)</span></a>
<!--        <a class="nav-item nav-link" href="#"><span class="glyphicon glyphicon-home"></span> Registrar</a>-->
<!--        <a class="nav-item nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-home"></span> Entrar</a>-->
      </div>
    </div>


    {% if user.is_authenticated %}
    Hola {{ user.username }}!
    <p><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-circle-arrow-left"></span> Logout</a></p>
    {% else %}
    <p></p>
    <a href="{% url 'login' %}"><span class="glyphicon glyphicon-circle-arrow-right"></span> Login</a>
    {% endif %}
  </nav>
  {% endblock %}

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="{% static 'js/app.js' %}"></script>


  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
{% block js %}
{% endblock js %}
  <script>
    $(document).ready(function () {
      $('#datatables').DataTable();
    });
  </script>
</body>

</html>

templates/sistema_escuela/home.html
{% extends 'sistema_escuela/base.html' %}


<title>{% block title %}Sistema Escuela - Inicio{% endblock %}</title>


{% block content %}

<!-- {% if user.is_authenticated %}
Hola {{ user.username }}!
<p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
<p>No estas Logeado</p>
<a href="{% url 'login' %}">login</a>
{% endif %} -->

<h1> Hola desde Home.Html</h1>
<p>Pellentesque pulvinar placerat tortor vitae malesuada. Mauris id mauris consectetur, bibendum quam eget, pulvinar
    ligula. In lobortis metus neque, rutrum laoreet orci consectetur sit amet. Ut tincidunt, justo at tincidunt
    ultrices, urna orci dignissim elit, eu egestas turpis augue id turpis. Ut quis blandit tellus. Sed posuere, elit ut
    porttitor ultricies, mi dui bibendum ipsum, eu fringilla libero orci ac lectus. Sed vel urna non mi pulvinar
    tincidunt. Nunc vitae lorem nec diam luctus facilisis nec ut justo. Mauris eget mauris consequat, vestibulum lorem
    ut, condimentum mi.</p>


{% endblock %}